---
# tasks file for k3s_worker
- name: Set k3s binary name based on architecture
  set_fact:
    k3s_binary_name: >-
      {% if ansible_architecture == 'aarch64' %}k3s-arm64
      {% elif ansible_architecture == 'armv7l' %}k3s-armhf
      {% else %}k3s
      {% endif %}

- name: Ensure k3s agent binary is present
  ansible.builtin.get_url:
    url: "https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/{{ k3s_binary_name }}"
    dest: /usr/local/bin/k3s
    mode: '0755'
    force: yes

- name: Create k3s config directory
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    mode: '0755'
    recurse: yes

- name: Deploy k3s agent systemd service file
  ansible.builtin.template:
    src: k3s-agent.service.j2
    dest: /etc/systemd/system/k3s-agent.service
    mode: '0644'
  notify: restart k3s-agent

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start k3s agent service
  ansible.builtin.service:
    name: k3s-agent
    state: started
    enabled: yes 