---
- name: Deploy k3s controllers
  hosts: controllers
  become: true
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/controllers.yml
  roles:
    - role: common
    - role: k3s_controller

- name: Deploy k3s workers
  hosts: workers
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/workers.yml
  become: true
  roles:
    - role: common
    - role: k3s_worker 