---
- name: Deploy k3s HA cluster
  hosts: all
  become: true
  roles:
    - role: common
      tags: common
    - role: k3s_controller
      when: controller_node | default(false)
      tags: controllers
    - role: k3s_worker
      when: not controller_node | default(false)
      tags: workers 