---
- name: Test k3s controller installation
  hosts: controllers
  become: true
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/controllers.yml
  roles:
    - role: common
    - role: k3s_controller 